//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payout.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayoutEntities : DbContext
    {
        public PayoutEntities()
            : base("name=PayoutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PAYOUTsecurityControlAccess> PAYOUTsecurityControlAccesses { get; set; }
        public virtual DbSet<PAYOUTsecurityModuleControl> PAYOUTsecurityModuleControls { get; set; }
        public virtual DbSet<PAYOUTsecurityModule> PAYOUTsecurityModules { get; set; }
        public virtual DbSet<PAYOUTsecurityRoleModuleControl> PAYOUTsecurityRoleModuleControls { get; set; }
        public virtual DbSet<PAYOUTsecurityUserModuleControl> PAYOUTsecurityUserModuleControls { get; set; }
    }
}
